OpenLiberty/guide-istio-intro

.travis.yml
They the tags are not showing the versions and the curl request is zipping the whole file. This guide is different than others. Check this issue https://github.ibm.com/was-liberty/openliberty-guides-team/issues/338
=> Removed OL tags and the curl request from travis.yml file

finish/inventory/src/main/java/io/openliberty/guides/inventory/InventoryManager.java, finish/inventory/src/main/java/io/openliberty/guides/inventory/InventoryResource.java, finish/inventory/src/main/java/io/openliberty/guides/inventory/model/InventoryList.java, finish/inventory/src/main/java/io/openliberty/guides/inventory/model/SystemData.java, start/inventory/src/main/java/io/openliberty/guides/inventory/InventoryManager.java, start/inventory/src/main/java/io/openliberty/guides/inventory/InventoryResource.java, start/inventory/src/main/java/io/openliberty/guides/inventory/model/SystemData.java
OpenLiberty/guides-common#95
OpenLiberty/guides-common#137
=> Refactor inventory

README.adoc, finish/inventory/src/test/java/it/io/openliberty/guides/inventory/InventoryVersionTest.java
* More specific description
* Remove 'Under the start directory'
* Make the system service description more specific
* Standardize 'cli' inconsistencies
* Remove 'In this guide' and 'x-version' header from intro
* Remove 'please'
* Fix Zipkin link
* Replace '/' with 'or'
* Change 'Create' statements to follow guidelines
* Remove directional words
* Make max line length 88 columns
* Re-order 'why use istio?' paragraphs to have all features listed first
=> Incorporate content review feedback

finish/inventory/pom.xml, finish/inventory/src/main/liberty/config/server.xml, finish/pom.xml, finish/system/pom.xml, finish/system/src/main/liberty/config/server.xml, start/inventory/pom.xml, start/inventory/src/main/liberty/config/server.xml, start/pom.xml, start/system/pom.xml, start/system/src/main/liberty/config/server.xml
Upgrade feature versions to fix the docker issue.
=> Upgrade feature versions

README.adoc, finish/pom.xml, start/pom.xml
Apply peer review feedback from #14
These are the changes for everything except the error occurring on Windows.
* Fix title and description
* Add explanation of bluen green deployments
* Remove commented out code in pom.xml
* Improve blue green deployment description
* Expand on first three paragraphs
* Capitalize Istio
* Add explanation of service mesh
* Combine sentences
* Re-word istio features sentence
* Add a routing example under the 'why istio?' section
* Remove blue green deployment sentence in 'why istio?' section
* Add note to increase memory amount if istio deployments do not become available
* Add note before out in deploy v1 section
* Move sentences around
* Apply feedback for 'deploying v2' section
* Add more detailed explanation for set-live script
* Apply feedback for …
=> Apply peer review feedback

.gitignore, README.adoc, finish/set-live, finish/set-live.bat, finish/src/main/java/io/openliberty/guides/rest/HelloApplication.java, finish/src/main/java/io/openliberty/guides/rest/HelloModel.java, finish/src/main/java/io/openliberty/guides/rest/HelloResource.java, finish/src/main/webapp/index.html, finish/src/test/java/it/io/openliberty/guides/rest/EndpointTest.java, start/src/main/java/io/openliberty/guides/rest/HelloApplication.java, start/src/main/java/io/openliberty/guides/rest/HelloModel.java, start/src/main/java/io/openliberty/guides/rest/HelloResource.java, start/src/main/webapp/index.html
Reduce spaces in docker images output
Ignore istio downloads
Show output of curl commands
Change tabs to spaces in set-live file
Change batch commands to lower case
Return exit code 1 on invalid input for set-live.bat
Bump duration to 20 minutes
Bump copyright year
=> Address content review feedback

README.adoc
Address feedback given by YK before the blue green deployment re-write. #12
=> Address YK's feedback

README.adoc
* Update related guides
* Increase time to 30 minutes
* Improve wording of `http://<ip-address>:<port>`
* Create a new paragraph
* Add no_copy role to HTTP responses
* Add 'Open Liberty' to 'Great work you are done!' section
#23  #24
=> User review

README.adoc
=> Update SEO description

finish/pom.xml, start/pom.xml
=> Upgrade dockerfile-maven-plugin

.travis.yml
=> Update slack token

README.adoc
Fix: https://github.com/OpenLiberty/guides-common/issues/99#issuecomment-459816019
Change 'testing' before nouns to 'test'
Re-structure envoy sentence
Re-structure and hyperlink Docker Compose sentence
Re-structure sentence about Istio's routing features
Re-structure sentence about telemetry
Add word 'by' to sentence
Re-structure sentence about mutual TLS
Hyperlink blue-green deployments
Remove 's' from 'features'
Re-structure sentence about traffic shifting
Remove 'is'
Re-structure sentence about environments
Fix comma usage in sentence about envs/deployments
Replace 'Once' with 'After'
Change "Next, deploy Istio’s resources..." to "Next, deploy Istio resources ...".
Change "...value of 1 once.... " to "...value of 1 after... ".
Change "Ensure that the Istio deployments are all available …
=> Apply ID review feedback

README.adoc
#46 
https://github.com/OpenLiberty/guides-common/pull/239
=> Add disclaimer about RAM usage earlier in the guide

README.adoc
=> Improve blue-green deployment description

.travis.yml
trigger auto test for qa branch
=> trigger auto test for qa branch

.travis.yml, README.adoc, finish/pom.xml, start/pom.xml
- Update README to use latest version of Istio
- Updated minikube start command to use newer version of Kubernetes supported by Istio
=> Update README to use latest version of Istio/kubernetes

README.adoc
=> Qa to master: fixed the command box at Tearing down section

README.adoc
Issue: https://github.com/OpenLiberty/guide-istio-intro/issues/71
=> fixed curl command

README.adoc
=> Merge qa to master: fix the curl commands

README.adoc, finish/Dockerfile, finish/pom.xml, scripts/travisTest.sh, start/Dockerfile, start/pom.xml
Removed spotify docker maven plugin, packageFile as tar.gz in pom.xml and updated Dockerfile to use ADD instruction
Addressing https://github.com/OpenLiberty/guides-common/issues/299
=> Docker updates

README.adoc
=> Merge qa to master: clear the teardown instructions

README.adoc
Based on peer-review feedback, change wording.
=> Modify "Deploying Istio" and "Teardown" section

README.adoc, finish/src/main/java/io/openliberty/guides/system/SystemResource.java, finish/src/test/java/it/io/openliberty/guides/system/SystemEndpointIT.java, start/src/main/java/io/openliberty/guides/system/SystemResource.java
- Hard coded version number as `public static` field.
- Changed README to ask users to manually update version number
- Changed integration test to use `APP_VERSION` static field
=> Hardcode version number

finish/pom.xml, start/pom.xml
- updated pom to address issue highlighted here: https://github.com/OpenLiberty/guides-common/issues/436
=> updated pom

finish/pom.xml, start/pom.xml
=> Merge qa to master: specify version directly in plugins

README.adoc, scripts/travisTest.sh
https://github.com/OpenLiberty/guides-common/issues/439
=> pull OL docker image

README.adoc
Reverts OpenLiberty/guide-istio-intro#99
=> Revert "Update k8 instruction"

README.adoc, scripts/travisTest.sh
=> Merge qa to master: revert  update k8 instruction

CONTRIBUTING.md, README.adoc
PR: #105 
Issue: OpenLiberty/guides-common#514
=> Merge qa to master: add cd start command

README.adoc
=> Merge qa to master: deploying istio update

.github/workflows/test.yml, scripts/startMinikube.sh
* Update test.yml
* fix juju permissions
* best practices
- PR: #114 
- Issue: https://github.com/OpenLiberty/guides-common/issues/532
=> Merge qa to master: Enable PR checker
